import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppSideBar from "@/component/AppSideBar";
import RightSideMenu from "@/component/RightSideMenu";
import { DataProvider } from "@/context/DataContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased w-[400px] sm:w-[602px]`}
      >
        <div className="flex flex-row h-screen w-screen bg-[#fff] justify-center ">
          <DataProvider>
          <AppSideBar />
          {children}
          <RightSideMenu />
          </DataProvider>
        </div>
      </body>
    </html>
  );
}
